In [2]:
from mxnet import nd

In [3]:
'''创建ndarray'''

'创建ndarray'

In [4]:
# 创建一个长度为12的一维数组
x = nd.arange(12)
# 通过shape获得其形状
x.shape
# 通过size获得其元素总数
x.size
# 改变arr的shape
X = x.reshape((3,4)) # or arr.reshape((-1,4)) or arr.reshape((3,-1))

In [5]:
# 创建一个形状为(2,3,4)，元素全为0的张量
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [6]:
# 创建一个形状为(2,3,4)，元素全为1的张量
nd.ones((2,3,4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [7]:
# 创建一个形状为(2,3,4)，元素随机采样于均值为0，标准差为1的正态分布的张量
nd.random.normal(0, 1, shape=(2,3,4))


[[[ 2.2122064   0.7740038   1.0434405   1.1839255 ]
  [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
  [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]

 [[ 0.2444218  -0.03716067 -0.48774993 -0.02261727]
  [ 0.57461417  1.4661262   0.6862904   0.35496104]
  [ 1.0731696   0.12017461 -0.9711102  -0.77569664]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
# 从list生成ndarray
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [9]:
'''运算'''

'运算'

In [10]:
# 逐元素相加
X + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [11]:
# 逐元素相减
X - Y


[[-2.  0. -2.  0.]
 [ 3.  3.  3.  3.]
 [ 4.  6.  8. 10.]]
<NDArray 3x4 @cpu(0)>

In [12]:
# 逐元素相乘
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [13]:
# 逐元素相除
X / Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [14]:
# 逐元素指数运算
X.exp()


[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02 1.0966332e+03]
 [2.9809580e+03 8.1030840e+03 2.2026465e+04 5.9874141e+04]]
<NDArray 3x4 @cpu(0)>

In [15]:
# 矩阵乘法
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [16]:
# 矩阵联结
nd.concat(X, Y, dim=0)
nd.concat(X, Y, dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [17]:
# 条件判断，得到一个元素为0或1的新ndarray
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [18]:
# 求和，得到一个单元素ndarray
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [19]:
# ndarray转换为python标量
X.norm().asscalar()

22.494442

In [20]:
'''广播机制'''

'广播机制'

In [21]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [22]:
'''索引'''

'索引'

In [23]:
# 切片
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [24]:
# 访问某个元素
X[1,2]


[6.]
<NDArray 1 @cpu(0)>

In [25]:
# 赋值
X[1:2, :] = 12

In [26]:
'''运算的内存开销'''

'运算的内存开销'

In [27]:
# 会开辟新内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [28]:
# X+Y还是会开辟新内存，但是结果会被copy给Z
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [29]:
# 减少了X+Y的内存开销
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [30]:
'''ndarray和numpy互换'''

'ndarray和numpy互换'

In [37]:
# numpy转ndarray
import numpy as np
P = np.ones((2, 3))
D = nd.array(P)

In [32]:
# ndarray转numpy
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [33]:
'''总结'''

'总结'

In [34]:
# 1. X.exp(), X.sum(), X.norm()也可以改写为nd.exp(X), nd.sum(X), nd.norm(X);
# 2. NDArray是MXNet中存储和变换数据的主要工具;
# 3. 可以轻松地对NDArray创建、运算、指定索引，并与NumPy之间相互变换。

In [35]:
'''练习'''

'练习'

In [36]:
# 1. 运行本节中的代码。将本节中条件判别式X == Y改为X < Y或X > Y，看看能够得到什么样的NDArray？
X < Y
# 2. 将广播机制中按元素运算的两个NDArray替换成其他形状，结果是否和预期一样？
A = nd.arange(3).reshape((3, 1))
B = nd.arange(3).reshape((1, 3))
A + B


[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
<NDArray 3x3 @cpu(0)>